# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7797994060d9db66881979ea0a7c705a8bfc300204e7a1c4c829a385a6f3395d4ac8004d0f674b4bc1f6b98764f3bfc44c4d0ae5de9771c38c8d8933a43ffa30

test:
  secret_key_base: 8c7a78f6f3d7c1faef3736b54f6aeed86c8b01e24db413dd4f0362c547cf9c47480dbfb26a3fe200d017af2b76caa21ad60097ca60b9491342cbab12f47a14aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
